routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\AcountInfoController;
use App\Http\Controllers\InvoiceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('client',ClientController::class);
Route::resource('invoice',InvoiceController::class);


Route::get('/account/edit',[AcountInfoController::class,'edit'])->name('accountinfo.edit');
Route::post('/account/edit',[AcountInfoController::class,'update'])->name('accountinfo.update');
Route::post('/invoice/paid/{id}', [InvoiceController::class, 'paid'])->name('invoice.paid');
Route::get('/invoice/downloadpdf/{id}', [InvoiceController::class, 'downloadPdf'])->name('invoice.download');

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->hasOne(User::class,'id', 'user_id');
    }

    public function client()
    {
        return $this->hasOne(Client::class, 'id', 'client_id');
    }

    public function items()
    {
        return $this->hasMany(InvoiceItem::class, 'invoice_id', 'id');
    }

    public function isLate()
    {

        $lastDay = date('Y-m-d', strtotime($this->created_at. ' +'.$this->payment_term.' days'));
        $today = date('Y-m-d');
        return $lastDay < $today;

    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\InvoiceItem;
use Illuminate\Http\Request;
use App\Models\Invoice;
use Illuminate\Support\Facades\Auth;
use App\Services\InvoiceService;
use PDF;
class InvoiceController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $invoices = Invoice::where('user_id', Auth::id())->get(); // pagination
        return view('invoice.index', compact('invoices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::where('active', 1)->where('user_id', Auth::id())->get();
        $user = Auth::user();
        return view('invoice.create', compact('clients', 'user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'client' => 'required|integer',
            'payment_term' => 'required|integer',
            'name.*' => 'required|max:255',
            'unit.*' => 'required|integer',
            'price.*' => 'required|numeric',
            'qty.*' => 'required|integer'
        ]);

        $userId = Auth::id();
        $service = new InvoiceService($userId);
        $invoice = new Invoice();
        $invoice->number = $service->getInvoiceNumber();
        $invoice->invoice_number = $service->getSerialNumber();
        $invoice->sum_excl_tax = 0;
        $invoice->sum_incl_tax = 0;
        $invoice->user_id = $userId;
        $invoice->client_id = $request->input('client');
        $invoice->payment_term = $request->input('payment_term');
        $invoice->save();

        $invoiceId = $invoice->id;
        foreach ($request->input('name') as $key => $invoiceLine) {
            $line = new InvoiceItem();
            $line->name = $invoiceLine;
            $line->invoice_id = $invoiceId;
            $line->price_incl_tax = $service->getPriceWithTax($request->input('price')[$key]);
            $line->price_excl_tax = $request->input('price')[$key];

            $line->qty = $request->input('qty')[$key];

            $invoice->sum_excl_tax += $line->price_excl_tax * $line->qty;
            $invoice->sum_incl_tax += $line->price_incl_tax * $line->qty;

            $line->unit_id = $request->input('unit')[$key];
            $line->save();
        }

        $invoice->save();

        return redirect(route('invoice.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $invoice = Invoice::find($id);
        return view('invoice.show', compact('invoice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // TODO anuliuoti
    }

    public function paid($id)
    {
        $invoice = Invoice::where('id',$id)->where('user_id', Auth::id())->firstOrFail();
        $invoice->paid = true;
        $invoice->save();
        return redirect()->back();
    }

    public function downloadPdf($id)
    {
        $invoice = Invoice::where('id',$id)->where('user_id', Auth::id())->firstOrFail();
        $pdf = PDF::loadView('invoice.pdf.invoice', compact('invoice'));
        return $pdf->download($invoice->invoice_number);
    }
}

resources/views/invoice/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @if($errors)
                    @foreach ($errors->all() as $error)
                        <div>{{ $error }}</div>
                    @endforeach
                @endif
                <div class="card">
                    <div class="card-header">{{ __('Invoice create') }}</div>
                    <div class="card-body">

                        <form method="POST" action="{{route('invoice.store')}}">
                            @csrf
                            @method('POST')
                            <div class="row">
                                <div class="col-6">
                                    <ul class="list-unstyled">
                                        <li>{{$user->info->first_name}}</li>
                                        <li>{{$user->info->last_name}}</li>

                                        <li>{{$user->info->address ?? '' }}</li>
                                        <li>{{$user->info->city->name ?? '' }}</li>
                                        <li>{{$user->info->post_code ?? '' }}</li>
                                        <li>{{$user->info->bank_account_number ?? '' }}</li>
                                    </ul>

                                </div>
                                <div class="col-6">
                                    <select name="client" id="client">
                                        <option>---------</option>
                                        @foreach($clients as $client)
                                            <option value="{{$client->id}}" data-url="{{route('client.show',$client->id)}}">
                                                {{$client->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                    <div id="client-wrapper">

                                    </div>
                                </div>
                            </div>
                            <div class="row" id="invoice-items">
                                <div class="col-12 invoice-line">
                                    <input required name="name[1]" placeholder="Paslauga/Preke">
                                    <input required class="line-price" name="price[1]" type="text" placeholder="Kaina">
                                    <input required class="line-qty" name="qty[1]" type="number" placeholder="Kiekis">
                                    <select name="unit[1]">
                                        <option value="1">Vnt</option>
                                        <option value="2">Val</option>
                                    </select>
                                    <input disabled name="sum[1]" value="30$">
                                </div>
                            </div>
                            <div class="btn btn-info add-invoice-line" id="add-invoice-line">+</div>

                            <div class="row">
                                <div class="col-6">
                                {{__('Term to pay')}} <input type="number" name="payment_term" placeholder="Expl. 15d">
                                </div>
                                <div class="col-6">
                                <input type="submit" class="btn btn-success" value="Create Invoice">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/invoice/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">

                <div class="card">
                    <div class="card-header">
                        <a  class="btn btn-info"
                            href="{{route('invoice.create')}}">
                            {{__('Create Invoice')}}
                        </a>
                    </div>
                    <ul class="list-group">
                        @foreach($invoices as $invoice)
                            <li class="list-group-item">
                                <a href="{{route('invoice.show',$invoice->id)}}">
                                    {{$invoice->invoice_number}}
                                    {{$invoice->client->name}}
                                    {{$invoice->created_at}}
                                    {{$invoice->sum_incl_tax}}
                                </a>
                                @if($invoice->isLate() && !$invoice->paid)

                                <span class="alert-danger">
                                    {{__('SKOLININKAS!!!!')}}
                                </span>
                                @endif
                                @if(!$invoice->paid)
                                    <form method="post" action="{{route('invoice.paid',$invoice->id)}}" style="float: right">
                                        @csrf
                                        @method('POST')
                                        <input type="submit" value="{{__('Paid')}}" class="btn btn-success">
                                    </form>
                                @endif
                            </li>
                        @endforeach
                    </ul>
                    {{--                    {{$clients->links()}}--}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/invoice/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><a href="{{route('invoice.download', $invoice->id)}}">download PDF</a> </div>
                    <div class="card-body">

                        <form method="POST" action="{{route('invoice.store')}}">
                            @csrf
                            @method('POST')
                            <div class="row">
                                <div class="col-6">
                                    <ul class="list-unstyled">
                                        <li>{{$invoice->user->info->first_name}}</li>
                                        <li>{{$invoice->user->info->last_name}}</li>

                                        <li>{{$invoice->user->info->address ?? '' }}</li>
                                        <li>{{$invoice->user->info->city->name ?? '' }}</li>
                                        <li>{{$invoice->user->info->post_code ?? '' }}</li>
                                        <li>{{$invoice->user->info->bank_account_number ?? '' }}</li>
                                    </ul>

                                </div>
                                <div class="col-6">
                                    <div id="client-wrapper">
                                        <ul class="list-unstyled">
                                            <li>{{$invoice->client->name}}</li>
                                            <li>{{$invoice->client->code}}</li>
                                            <li>{{$invoice->client->address}}</li>
                                            <li>{{$invoice->client->city->name}} {{$invoice->client->post_code}}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="row" id="invoice-items">

                                    <div class="col-3">
                                        {{__('Name')}}
                                    </div>
                                    <div class="col-3">
                                        {{__('Price')}}
                                    </div>
                                    <div class="col-3">
                                        {{__('Qty')}}
                                    </div>
                                    <div class="col-3">
                                        {{__('Sum')}}
                                    </div>

                                @foreach($invoice->items as $item)

                                        <div class="col-3">
                                            {{$item->name}}
                                        </div>
                                        <div class="col-3">
                                            {{$item->price_incl_tax}}
                                        </div>
                                        <div class="col-3">
                                            {{$item->qty}}
                                        </div>
                                        <div class="col-3">
                                            {{$item->price_incl_tax * $item->qty}}
                                        </div>

                                @endforeach

                            </div>

                            <div class="row">
                                <div class="col-6">
                                    {{__('Term to pay')}} <input type="number" name="payment_term"
                                                                 placeholder="Expl. 15d">
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection