routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\AcountInfoController;
use App\Http\Controllers\InvoiceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('client',ClientController::class);
Route::resource('invoice',InvoiceController::class);


Route::get('/account/edit',[AcountInfoController::class,'edit'])->name('accountinfo.edit');
Route::post('/account/edit',[AcountInfoController::class,'update'])->name('accountinfo.update');
Route::post('/invoice/paid/{id}', [InvoiceController::class, 'paid'])->name('invoice.paid');
Route::get('/invoice/downloadpdf/{id}', [InvoiceController::class, 'downloadPdf'])->name('invoice.download');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    public function city()
    {
        return $this->hasOne(City::class,'id', 'city_id');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClientController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::where('active', true)->where('user_id', Auth::id())->get();
//        $clients  = Client::where('active',1)->where('user_id', Auth::id())->paginate(2);

        return view('client.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required|max:20|min:2',
            'code' => 'required|max:20',
            'vat_code' => 'max:20',
            'address' => 'required|max:160',
            'city' => 'required|integer',
            'post_code' => 'required|max:8',
            'email' => 'email',
            'phone' => 'max:14',
        ]);

        $client = new Client();
        $client->name = $request->input('name');
        $client->code = $request->input('code');
        $client->vat_code = $request->input('vat_code');
        $client->address = $request->input('address');
        $client->city_id = $request->input('city');
        $client->user_id = Auth::id();
        $client->post_code = $request->input('post_code');
        $client->email = $request->input('email');
        $client->phone = $request->input('phone');
        $client->comment = $request->input('comment');
        $client->save();

        return redirect(route('client.index'));

    }
    // adress_enty

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = Client::where('id', $id)->where('user_id', Auth::id())->where('active', true)->firstOrFail();
        $htmlBlock = view('client.show', compact('client'))->render();
        return response()->json(['succsess' => true, 'html' => $htmlBlock]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::where('id', $id)->where('user_id', Auth::id())->where('active', true)->firstOrFail();

        return view('client.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'name' => 'required|max:20|min:2',
            'code' => 'required|max:20',
            'vat_code' => 'max:20',
            'address' => 'required|max:160',
            'city' => 'required|integer',
            'post_code' => 'required|max:8',
            'email' => 'email',
            'phone' => 'max:14',
        ]);

        $client = Client::where('id', $id)->where('user_id', Auth::id())->where('active', true)->firstOrFail();

        $client->name = $request->input('name');
        $client->code = $request->input('code');
        $client->vat_code = $request->input('vat_code');
        $client->address = $request->input('address');
        $client->city_id = $request->input('city');
        $client->post_code = $request->input('post_code');
        $client->email = $request->input('email');
        $client->phone = $request->input('phone');
        $client->comment = $request->input('comment');
        $client->save();

        return redirect(route('client.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::where('id', $id)->where('user_id', Auth::id())->firstOrFail();
        $client->active = false;
        $client->save();
        return redirect(route('client.index'));
    }
}

resources/views/client/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form class="form" method="post" action="{{route('client.store')}}">
                    @csrf
                    @method('POST')
                    <div class="form-group row">
                        <label for="name"
                               class="col-md-4 col-form-label text-md-right">{{ __('Client Name') }}</label>

                        <div class="col-md-6">
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name"
                                   value="{{old('name')}}"
                                   required autocomplete="name">

                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="code"
                               class="col-md-4 col-form-label text-md-right">{{ __('Company Code') }}</label>

                        <div class="col-md-6">
                            <input id="code" type="text"
                                   class="form-control @error('code') is-invalid @enderror"
                                   name="code"
                                   value="{{old('code')}}"
                                   required autocomplete="code">

                            @error('code')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="address"
                               class="col-md-4 col-form-label text-md-right">{{ __('Address line') }}</label>

                        <div class="col-md-6">
                            <input id="address" type="text"
                                   class="form-control @error('address') is-invalid @enderror"
                                   name="address"
                                   value="{{old('address')}}"
                                   required autocomplete="address">

                            @error('address')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="city" class="col-md-4 col-form-label text-md-right">{{ __('City') }}</label>

                        <div class="col-md-6">
                            <select name="city" class="form-control">
                                <option value="1">Vilnius</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="post_code"
                               class="col-md-4 col-form-label text-md-right">{{ __('Post Code') }}</label>

                        <div class="col-md-6">
                            <input id="post_code" type="text"
                                   class="form-control @error('post_code') is-invalid @enderror"
                                   name="post_code"
                                   value="{{old('post_code')}}"
                                   required autocomplete="post_code">

                            @error('post_code')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="vat_code" class="col-md-4 col-form-label text-md-right">{{ __('TAX VAT ID') }}</label>

                        <div class="col-md-6">
                            <input id="vat_code" type="text" class="form-control @error('vat_code') is-invalid @enderror"
                                   name="vat_code"
                                   value="{{old('vat_code')}}"
                                   autocomplete="vat_code">

                            @error('vat_code')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                   name="email"
                                   value="{{old('email')}}"
                                   required autocomplete="email">

                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                        <div class="col-md-6">
                            <input id="phone" type="tel" class="form-control @error('phone') is-invalid @enderror"
                                   name="phone"
                                   value="{{old('phone')}}"
                                   autocomplete="phone">

                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="comment" class="col-md-4 col-form-label text-md-right">{{ __('Comment') }}</label>

                        <div class="col-md-6">
                            <textarea class="form-control @error('comment') is-invalid @enderror"
                                      name="comment">{{old('comment')}}</textarea>


                            @error('comment')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="input-group">
                        <input type="submit" class="btn btn-success" value="{{__('Create')}}">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/client/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form class="form" method="post" action="{{route('client.update', $client->id)}}">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                        <label for="name"
                               class="col-md-4 col-form-label text-md-right">{{ __('Client Name') }}</label>

                        <div class="col-md-6">
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name"
                                   value="{{$client->name}}"
                                   required autocomplete="name">

                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="code"
                               class="col-md-4 col-form-label text-md-right">{{ __('Company Code') }}</label>

                        <div class="col-md-6">
                            <input id="code" type="text"
                                   class="form-control @error('code') is-invalid @enderror"
                                   name="code"
                                   value="{{$client->code}}"
                                   required autocomplete="code">

                            @error('code')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="address"
                               class="col-md-4 col-form-label text-md-right">{{ __('Address line') }}</label>

                        <div class="col-md-6">
                            <input id="address" type="text"
                                   class="form-control @error('address') is-invalid @enderror"
                                   name="address"
                                   value="{{$client->address}}"
                                   required autocomplete="address">

                            @error('address')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="city" class="col-md-4 col-form-label text-md-right">{{ __('City') }}</label>

                        <div class="col-md-6">
                            <select name="city" class="form-control">
                                <option value="1">Vilnius</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="post_code"
                               class="col-md-4 col-form-label text-md-right">{{ __('Post Code') }}</label>

                        <div class="col-md-6">
                            <input id="post_code" type="text"
                                   class="form-control @error('post_code') is-invalid @enderror"
                                   name="post_code"
                                   value="{{$client->post_code}}"
                                   required autocomplete="post_code">

                            @error('post_code')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="vat_code"
                               class="col-md-4 col-form-label text-md-right">{{ __('TAX VAT ID') }}</label>

                        <div class="col-md-6">
                            <input id="vat_code" type="text"
                                   class="form-control @error('vat_code') is-invalid @enderror"
                                   name="vat_code"
                                   value="{{$client->vat_code}}"
                                   autocomplete="vat_code">

                            @error('vat_code')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                   name="email"
                                   value="{{$client->email}}"
                                   required autocomplete="email">

                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                        <div class="col-md-6">
                            <input id="phone" type="tel" class="form-control @error('phone') is-invalid @enderror"
                                   name="phone"
                                   value="{{$client->phone}}"
                                   autocomplete="phone">

                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="comment" class="col-md-4 col-form-label text-md-right">{{ __('Comment') }}</label>

                        <div class="col-md-6">
                            <textarea class="form-control @error('comment') is-invalid @enderror"
                                      name="comment">{{$client->comment}}</textarea>


                            @error('comment')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="input-group">
                        <input type="submit" class="btn btn-success" value="{{__('Edit')}}">
                    </div>
                </form>
                <br>
                <form action="{{route('client.destroy', $client->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <input type="submit" class="btn btn-danger" value="{{__('Delete')}}">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/client/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">

                <div class="card">
                    <div class="card-header">
                        <a  class="btn btn-info"
                            href="{{route('client.create')}}">
                            {{__('Create new client')}}
                        </a>
                    </div>
                    <ul class="list-group">
                    @foreach($clients as $client)
                        <li class="list-group-item">
                            <a href="{{route('client.edit',$client->id)}}">
                                {{$client->name}}
                            </a>
                        </li>
                    @endforeach
                    </ul>
{{--                    {{$clients->links()}}--}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/client/show.blade.php
<ul class="list-unstyled">
    <li>
        <b>
            {{$client->name}}
        </b>
    </li>
    <li>
        <i>
            {{$client->code}}
        </i>
    </li>
    <li>
        {{$client->vat_code}}
    </li>
    <li>
        {{$client->address}}
    </li>
</ul>